version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build: # this can be any name you choose
    docker:
        - image: cimg/node:16.15.0
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
            - cache-{{ checksum "package.json" }}
        - run:
              name: Install Dependencies
              command: npm ci
        - save_cache:
            key: cache-{{ checksum "package.json" }}
            paths:
            - node_modules
        - run:
              name: Run Build
              command: npm run build
        - run: 
            name: firebase deploy
            command: npm install --save-dev firebase-tools
        - run: 
            name: please deploy 
            command: firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  test_my_app:
    jobs:
      - build
      

