version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build: # this can be any name you choose
    docker:
        - image: circleci/node:12.18.3
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys:
            - cache-{{ checksum "package.json" }}
        - run:
              name: Install Dependencies
              command: npm ci
        - save_cache:
            key: cache-{{ checksum "package.json" }}
            paths:
            - node_modules
        - run:
              name: Run Build
              command: npm run build
      # - node/install:
      #     node-install-dir: ~ 
      # - node/run:
      #     pkg-manager: npm 
      #     npm-run: build 
      

workflows:
  test_my_app:
    jobs:
      - build
      

