version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application for production
          command: npm run build
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
             - run:
                name: Firebase Deploy
                command: |
                  ./node_modules/.bin/firebase use portfolio --token=$FIREBASE_DEPLOY_TOKEN
                  ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting -m "$CIRCLE_BUILD_NUM"
workflows:
  build-and-deploy:
    jobs:
      - build
