version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build: # this can be any name you choose
    docker:
      - image: circleci/current
    steps:
      - checkout
      - node/install:
            node-install-dir: ~ 

workflows:
  test_my_app:
    jobs:
      - build
      - node/run:
          pkg-manager: npm 
          npm-run: build 

